"use client"
import './globals.css'
import { Manrope } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import "../../public/css/style.css"
import "../../public/css/responsiveStyle.css"
import Header from '@/app/Components/Header/Header'
import Footer from '@/app/Components/Footer/Footer'
const manrope = Manrope({ subsets: ['latin'] })

const metadata = {
  title: 'e Broker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />

      </head>
      <body className={manrope.className}>
        <Header />
        {children}
        <Footer />
        <div id="panorama"></div>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>

        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>
        <script src="https://cdn.jsdelivr.net/npm/aframe@1.4.2/dist/aframe.min.js"></script>
      </body>


    </html>
  )
}
