"use client"
import './globals.css'
import { Manrope } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import "../../public/css/style.css"
import "../../public/css/responsiveStyle.css"
import Header from '@/app/Components/Header/Header'
import Footer from '@/app/Components/Footer/Footer'
import { Provider } from 'react-redux'
import { store } from '../store/store'
import Head from 'next/head'
const manrope = Manrope({ subsets: ['latin'] })

const metadata = {
  title: 'e Broker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>eBroker</title>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
      </head>
      <body className={manrope.className}>
        <Provider store={store}>

          <Header />
          {children}
          <Footer />

        </Provider>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>

      </body>


    </html>
  )
}
